### ISSUE TITLE
Above Parameters, a section for "who ran it, when, and how long it took"

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#1]

**Comment by zsimpson** [comment]
I can show who ran it and when but I don't know how long it took because I don't get callbacks from SGE for example.

**Comment by kdemarest** [comment]
Maybe each task could note when it started and ended.  You must know that because you show it on the web page... Oh, but maybe you only do that when the web page is polling?  Perhaps when we add the SGE qstat we'd see runtime...

**Comment by kdemarest** [comment]
No a tragedy if we don't have this, but a client mentioned it.

**Comment by zsimpson** [comment]
I added who ran it and when they started it.  I can only get end time from rhino not SGE and even then I'd have to implement callbacks.  So I'm punting on that aspect.
