### ISSUE TITLE
appname and name of app and the folder name are redundant.

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#105]
Need a better way to do this.

**Comment by kdemarest** [comment]
I think we need to leave the folder name as a separate entity. Others could merge.

**Comment by zsimpson** [comment]
The issue is that when you POST to welder I don't know anything about what folder that app was in.  But for "run similar" to work I need to know that information. So right now there's "name" which is what will be shown with the 0123-some_name stuff.  Then there's the name of the folder which doesn't have to be the same. BUT I have to know that folder name for run similar for that's what "appname" is.  Maybe we need a requirement that 

How about this.  If you specify "app_folder_name" then I use that on the "run similar". If I don't find that I look in folder "name" and if that's not found then I error.

**Comment by zsimpson** [comment]
After code review I decided to just rename "appname" to "appFolderName". It is still required if you want to use "run simular"
