### ISSUE TITLE
Editor's file list is empty on my OSX

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#106]
If I just click on the Editor tab, with a valid and full project, this is the result:

![image](https://cloud.githubusercontent.com/assets/2153005/8145147/712713e0-11c1-11e5-8480-3981fb339bdb.png)

**Comment by zsimpson** [comment]
CNR. I just tried in OSX and it worked fine.  I was on dev. What were you on?

**Comment by kdemarest** [comment]
It was a trailing slash problem. I fixed it.
