### ISSUE TITLE
Figure out progress indicator

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#126]
Need a way to monitor progress.  Even if it means polling or hitting refresh on stdout or something better than clicking on the task line item and bringing up the dialog box.

**Comment by zsimpson** [comment]
I'm thinking on the run status page there would be a new section called "monitor" with alinks to "Monitor stdout" and "Monitor stderr". If you click on one then it starts a polling loop that updates the section.

**Comment by AgustinCB** [comment]
https://github.com/appsoma/welder/pull/206
