### ISSUE TITLE
On editor, need a "repeat last run" to speed up development

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#131]

**Comment by zsimpson** [comment]
This would really speed me up

**Comment by zsimpson** [comment]
Even better there'd be a "Run with same parameters exactly" so you wouldn't even have to press submit on the app.

**Comment by kdemarest** [comment]
"Run Similar" vs "Repeat"

**Comment by AgustinCB** [comment]
https://github.com/appsoma/welder/pull/193
