### ISSUE TITLE
Important: need a way to allow installs to pull versioned updates

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#133]
For example, Jordan needs to be able to pull, with a version tag.

**Comment by zsimpson** [comment]
In what context do you mean this?  Welder has no pull concept right now.  If you want a submodule with a specific tag, that's normal submodule behavior.

**Comment by kdemarest** [comment]
I mean git cloning a project. Just that. Those using Appsoma to use
Jordan's pipeline will need a way to get it when he makes updates

On Friday, June 26, 2015, Zack Booth Simpson <notifications@github.com>
wrote:

> In what context do you mean this? Welder has no pull concept right now. If
> you want a submodule with a specific tag, that's normal submodule behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appsoma/welder/issues/133#issuecomment-115904742>.
>


-- 
*Ken Demarest*
ken.demarest@gmail.com
415.342.9731
Austin, Texas ▪ United States

**Comment by zsimpson** [comment]
That's just plain old git. WE have no git interface yet

**Comment by zsimpson** [comment]
I'm still not seeing what this is or why this is p1. I doubt you are suggesting that we go implement a whole GUI for git. So, I'm not sure what you're asking for.

**Comment by zsimpson** [comment]
Still don't know what this is about.

**Comment by kdemarest** [comment]
Import meets this need
