### ISSUE TITLE
burn dialog has an [ok], but what does it do?

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#134]
If you click it, it should warn "The docker burn will continue after you close."

**Comment by zsimpson** [comment]
It closes the dialog.  Maybe rename it do "close"?

**Comment by kdemarest** [comment]
sure. And get rid of the [cancel] button, because there is no cancelling the operations you start there

**Comment by kdemarest** [comment]
Yes, but we also need to unambiguously tell the user what is going on. Perhaps the top of the dialog could say: "Container save progress:" and then when it is done a line could say "Container save is complete."

**Comment by zsimpson** [comment]
Change button to "close" and set header to "Container Save in Progress"
