### ISSUE TITLE
OK button on data tab needs to handle uploads

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#137]
clicking OK when the Upload button is lit should just start the upload, and not close the window.

After upload auto-select whatever you just uploaded, if its a single file

Also, upload requires the page not change. Do we warn if you try to leave the page while an upload is in progress?

**Comment by zsimpson** [comment]
I added a warning if you try to hit ok if you have pending uploads.

Selecting the file after the upload is a lot harder so I decided to punt on that.
