### ISSUE TITLE
editor save seemed to fail while working with Jordan

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#138]

**Comment by zsimpson** [comment]
I think it has something to do with clicking on other folders and it ends up saving the file silently to a different folder as I've seen spurious copies of files laying around.

**Comment by zsimpson** [comment]
Yes. to repro.

Reload editor page.
Pick a file to edit
Now pick a different folder on the left
Hit Save
Reload editor page.  The file was saved to the wrong folder.

**Comment by zsimpson** [comment]
Fixed
