### ISSUE TITLE
Write tutorial

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#140]
Basis:
https://docs.google.com/document/d/1ThOXzqAO6bUxgasP_1_rY0dZ15Iaf0HviiUmXjRfHsI/edit

**Comment by zsimpson** [comment]
Do you think this should be in markdown like other docs?

**Comment by kdemarest** [comment]
yes.  Do you want to take it? I was thinking about doing this weekend,
though I have plenty of other things I'm doing...

*Ken Demarest*
ken.demarest@gmail.com
415.342.9731
Austin, Texas ▪ United States

**Comment by zsimpson** [comment]
im happy to take it but cant start till monday.

**Comment by zsimpson** [comment]
v1 at least is done.
