### ISSUE TITLE
editor page needs a mkdir button to support the tutorial

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#141]
The one thing we had to leave the browser interface for would have been this (until it was time to do version control work...)

So editor page needs a "New Folder" button.

**Comment by zsimpson** [comment]
I think we're going to have the mark one folder on the left as "selected" so that we know where we're creating it. Otherwise we'll have to make right-click menu on the tree view.

**Comment by zsimpson** [comment]
Done
