### ISSUE TITLE
Project tab needs Import Project button

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#143]
All it does is a git clone from whatever repo you name. Simple.

**Comment by zsimpson** [comment]
Not so simple because repros require credentials unless you use git://. So presumably we'd have to require that.

**Comment by kdemarest** [comment]
Yeah, could be. Or just require credentials, because the only people likely to do this are the ones who already own the AWS account, and can see out open source.  If they don't like it, they can let us know.

**Comment by zsimpson** [comment]
But you can't just require credentials. Github works by ssh keys. You'd have to make a key and post it to github as far as I know.

**Comment by zsimpson** [comment]
https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by AgustinCB** [comment]
@kdemarest @zsimpson 

I think is simpler use that solution: 

https://github.com/appsoma/welder/pull/213

Using ssh keys per host would allow import github projects and from any other host or server in which you have git repos (for example, private hosts in a private network). And maybe on future on other repository systems.

**Comment by zsimpson** [comment]
It has one now.
