### ISSUE TITLE
graph file reporting error 500

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#16]
Trying to retrieve the image "marker_green", which exists in the directory and which I gave permissions 777 just to be sure, produces an error 500:

GET http://mesos.appsoma.com:8088/projects/zack/apps/marker_green.png 500 (Internal Server Error)

this is because the server is looking in the /apps/ directory, not in /apps/global where my real origin is.

**Comment by kdemarest** [comment]
I think I figured it out. The file is simply not found. This should be, what, a status 404 I think. Only a server internal error should generate 500.

**Comment by zsimpson** [comment]
Fixed
