### ISSUE TITLE
Bad error message on bad user ids

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#177]

**Comment by zsimpson** [comment]
The problem turned out to be that the users were screwed up. The slave showed a numeric uid.  The 126 return is very mysterious. Not sure who is returning that. Docker? Mesos?  Need to research to improve error message.

**Comment by kdemarest** [comment]
To be precise, this bug is now "Show meaningful error messages under "Scheduler Stderr" on the task status page when docker or mesos have a failure."

**Comment by vernonm** [comment]
Users and docker errors are better.
