### ISSUE TITLE
task status should show the actual command

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#179]
When looking at the status of a particular task in Welder, it would be helpful for debugging if it reported the actual command it finally ran, eg the full docker command with all the -v mounts and everything.

That way I could more easily simulate manually what it was doing for me and find problems in Welder.

Perhaps somewhere in the "Scheduler Info"?

![image](https://cloud.githubusercontent.com/assets/2153005/8574186/09835494-255b-11e5-91e1-496d96c09922.png)

**Comment by kdemarest** [comment]
I just realized that what might be even more interesting is if, from the Task Status, there was a way to shell directly into a replica of the container that task was using. In other words, I'd click "Shell into Container" and it would run the exact same docker but instead of executing start.bash I'd find myself on the Container tab in the shell. That would be amazing.

**Comment by vernonm** [comment]
Most of the command line is constructed by Mesos (in the docker executor),
not by Welder or Rhino or Marathon.  That would be nice, but it's also
adding a lot of parsing.

**Comment by zsimpson** [comment]
As Mark says, I don't know what that is. I can guess, but I can't get the exact string.

**Comment by kdemarest** [comment]
I put it down at p2 until we have more evidence it is needed.

**Comment by vernonm** [comment]
The string never exists.  We do not seem to have required this detail anyway.
