### ISSUE TITLE
MemoryHog fails

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#182]
on welder_demo:
	
undefined is not a function
Path	
/api/v1/projects/demo_project/runs
Trace	
    at /opt/welder/api/welder_utility.js:402:4
    at /opt/welder/node_modules/async/lib/async.js:251:17
    at async.eachSeries (/opt/welder/node_modules/async/lib/async.js:142:20)
    at _asyncMap (/opt/welder/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/opt/welder/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/opt/welder/node_modules/async/lib/async.js:605:19)
    at Object.exports.danger.mkdir (/opt/welder/api/welder_utility.js:400:9)
    at /opt/welder/api/welder_runs.js:479:19
    at /opt/welder/node_modules/async/lib/async.js:607:21

**Comment by kdemarest** [comment]
The problem is passing a null to in:
	mkdir: function( user, path, callback ) {

however, it appears the caller is sendinf a valid callback:

```
				if( ! usesContainer ) {
					// SYMLINK params, results and CREATE outputs
					taskFunctions.push( function(callback) {
						var resultsFolder = path.join(folders.hostRunFolder,'results');

						util.danger.mkdir( user, containerRunFolder+"/outputs", function(err) {
							if( err ) return callback( err );

							util.danger.symLink( user, resultsFolder, containerRunFolder+"/results", function(err) {
								if( err ) return callback( err );
								callback();
							});
						});
					});
				}
```

**Comment by kdemarest** [comment]
especially mystifying because, upon entry to mkdir(), this happens:

assert( callback, "Callback "+callback+" invalid" );

So the callback should definitely not be undefined.

**Comment by AgustinCB** [comment]
Can't reproduce. Running memoryhug doesn't give me any error (or output, by the way).
