### ISSUE TITLE
Bad write permssion on a file editor does not give good error message

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#186]
Edit a file you can not write to. Hit save. It doesn't clear the drity flag (good) but doesn't give any error message (bad).

**Comment by zsimpson** [comment]
Something to do with this error in console
Uncaught TypeError: responseObject.trace.split is not a function

**Comment by AgustinCB** [comment]
Seems to be having with other error handling cases. For example, trying to add an app with name "óñññ".

**Comment by AgustinCB** [comment]
https://github.com/appsoma/welder/pull/191
