### ISSUE TITLE
improper nan.h noide's module called "chokidar" when it tries to use "fsevents"

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#19]
I had to remove noide from my version - it never compiled.  Tried a LOT of things to fix this, but nothing helped.  Here is what it isn't:
* It isn't the version of nan being included by welder
* It isn't a bad nan.h somewhere on a stray path

fsevent relates to watchfiles, I believe.

it looks like the module "chokidar" has a completely freaky fsevents dependency, here:

"dependencies": {
    "fsevents": "github:pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138",
    "recursive-readdir": "0.0.2"
  },

Here is the output:

> fsevents@0.2.1 install /Users/ken/welder/node/node_modules/noide/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^

**Comment by kdemarest** [comment]
I turns out I had to make custom fix to noide's module "chokidar", altering noide's package.json to use:
"chokidar": "^1.0.0"

This fixed it, and I've submitted a PR to the noide author.

**Comment by zsimpson** [comment]
Noide removed. Closing
