### ISSUE TITLE
"Task Name" mismatch under "Use Parameters and Input files" section

### ISSUE THREAD

**Issue by jyoti-pandey** [appsoma/welder#197]
While going through the tutorial, under "Use Parameters and Input files" section at No.13 noticed some mismatch...
The tutorial says "Task name" as "hello" whereas the actual "Task name" is "task_1"

![image](https://cloud.githubusercontent.com/assets/6119878/8762476/67528c2a-2d3f-11e5-9690-25c956d022a1.png)

**Comment by kdemarest** [comment]
fixed
