### ISSUE TITLE
Tutorial Stdout different than the actual under "Write Code" section

### ISSUE THREAD

**Issue by jyoti-pandey** [appsoma/welder#198]
Under "Write Code" section No. 15
Tutorial says - In the dialog, you will see the stdout as "Hello. I see you entered Welder!"

whereas the actual Stdout is -
Converted
This is some sample data to
This is some s(FROG)mple d(FROG)t(FROG)

Here is a screenshot -

![image](https://cloud.githubusercontent.com/assets/6119878/8766633/30f6f5ae-2e06-11e5-9071-e1a1f86b586b.png)

**Comment by kdemarest** [comment]
fixed
