### ISSUE TITLE
Tutorial output different than actual under "Make a Multi-Task Run" section

### ISSUE THREAD

**Issue by jyoti-pandey** [appsoma/welder#199]
Under "Make a Multi-Task Run" section No. 7

Tutorial says -  Click on View details of task_2 and see the output of the wordcount (wc) tool: 1 3 19 ./inputs/from_task_1

whereas the actual Stdout is:  0  5 24 ./inputs/from_task_1

![image](https://cloud.githubusercontent.com/assets/6119878/8766885/05076308-2e0f-11e5-8c14-cd4e3aa83534.png)

**Comment by kdemarest** [comment]
fixed
