### ISSUE TITLE
Running an app is not working on http://appsoma_demo.appsoma.com/

### ISSUE THREAD

**Issue by jyoti-pandey** [appsoma/welder#201]
- Create a new Project
- Create a new App
- Click on the app to run
- Clicking on the "Submit" button does not show any output

![image](https://cloud.githubusercontent.com/assets/6119878/8779237/03d8fb5e-2ec8-11e5-8055-3fa7e8d5feaa.png)

**Comment by vernonm** [comment]
This was an issue with the Rhino framework not running.  Fixed.
