### ISSUE TITLE
Cannot connect to a new container at http://appsoma_demo.appsoma.com/

### ISSUE THREAD

**Issue by jyoti-pandey** [appsoma/welder#202]
- Started a New container with Image "Ubuntu"
- Clicking "Connect" on the row does not show the bash terminal 

![image](https://cloud.githubusercontent.com/assets/6119878/8781724/772ac8a4-2ed6-11e5-8226-31ed6db27d75.png)

**Comment by vernonm** [comment]
The container "connect" does not work with the new service discovery approach we're working on.  The link to connect will need to take into account etcd/haproxy

**Comment by kdemarest** [comment]
When new service discovery is in place, lets get this working again.

**Comment by vernonm** [comment]
Container Connect is fixed with better service discovery and config
