### ISSUE TITLE
Editor: wrong code shows up on new file

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#203]
Create a new file
Switch to a different file, copy the contents of that file in preparation for pasting into the new file you jsut made
Return to the new file you made
There's code in there! Where did it come from?

**Comment by AgustinCB** [comment]
I can't reproduce. But if you wrote something on a new file, don't save and switch to another file, it stores the unsaved changes into the browser and when you come back, it shows it again to you.

Is it possible that's what happened?

**Comment by kdemarest** [comment]
Unlikely this still exists.
