### ISSUE TITLE
Halted containers should also show in container list

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#21]
Such containers should get:

* Instead of a [Connect] button they will get a [Resume] button.
* They still get a Delete and Save button
* Status column should read "Paused"

**Comment by zsimpson** [comment]
Not sure what this means. There is a "pause" container in docker but we have no UI for it.  Are you saying that we should have UI to pause a container? I'm not sure what problem this solves.

**Comment by kdemarest** [comment]
If I start container "ubuntu" and then add a new file "happy" within it, when I exit from that container the process for that container stops running.  Fine.

But what about any changes to the file system? It turns out that any files created continue to exist, at least in some form. For example, when using aufs, if my running container's uid is 

4eed7b5dc5a4bb699930cdb7d0810ead790689518fffea4de5ebb1fddeec915f

then after I exit the container, this file still exists:

var/lib/docker/aufs/diff/4eed7b5dc5a4bb699930cdb7d0810ead790689518fffea4de5ebb1fddeec915f/happy

Does that imply the container can be re-started and see this file?  Or does it imply that docker is leaving chaff lying around on the disk?

**Comment by vernonm** [comment]
Container != Image.  Everything we've done is `docker run image do_stuff.sh`.  That creates a container `xyz0ff` on the machine (or, y'know, with a helpful name you specify).  That container has a persistent disk space on that machine.  It can be stopped, started, restarted, etc.  It only goes away on `docker kill xyz0ff`.  That container can be burned to an image, and then pushed somewhere too. 

We have never reused containers.  It would be possible, though potentially dangerous, to offer users the ability to stop and restart containers.    Note that a "container" only lives on the single machine it started on.  If you can't get that mesos node back, you can't restart that container...

**Comment by zsimpson** [comment]
I agree w Mark. Closing
