### ISSUE TITLE
End of saving a container is odd

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#22]
A few tweaks:

1. No need for OK and Cancel to exist, because you can't really cancel after the save has started

2. While saving, the readout is gradually adding lines, yet there is no indication that the save is not yet complete. I wonder whether we should disable the [ok] button and make it say "Saving..." and only turn it to [OK] once complete.

3. Most importantly, after writing all the lines of the saving process, that content cleared and I was left with an empty modal box (with the title and [ok] still showing, but the text gone - see screenshot below)

4. When I attempted to save the same container a second time, I only got the blank modal shown below.

![image](https://cloud.githubusercontent.com/assets/2153005/7736008/b2ec44c6-ff06-11e4-9984-54c30bf119a5.png)

**Comment by kdemarest** [comment]
When I checked the docker hub repo later, the first existed and the second and third did not exist.

**Comment by zsimpson** [comment]
It now closes the modal.
