### ISSUE TITLE
New projects have blank dataset, meaning upload fails

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#220]
Uploading will attempt to put the file in a dataset called "null", and fail:

![image](https://cloud.githubusercontent.com/assets/2153005/8990271/bbde8a70-36b6-11e5-8a26-fc45e9db63dd.png)

![image](https://cloud.githubusercontent.com/assets/2153005/8990277/c643c250-36b6-11e5-879b-da47389d3034.png)

**Comment by kdemarest** [comment]
Strangely, after creating a dataset called "logo" and then drag/drop and starting Upload, I get this error:

![image](https://cloud.githubusercontent.com/assets/2153005/8990313/f4d5bf9c-36b6-11e5-806f-470a0ce2911e.png)

**Comment by zsimpson** [comment]
I disabled upload on empty dataset now.
