### ISSUE TITLE
"Edit" link on the Apps page does not open the clicked app file and instead shows previously opened file in the Editor

### ISSUE THREAD

**Issue by jyoti-pandey** [appsoma/welder#225]
- Opened a file in the Editor "/apps/hello_world/index.html"
- Then created a new app "multi_task"
- If I click on the "Edit" link on the app "multi_task" on Apps page, it shows the previously opened file "/apps/hello_world/index.html"

![image](https://cloud.githubusercontent.com/assets/6119878/9068343/9462842e-3aa8-11e5-8efa-d5d1c4b964d8.png)

![image](https://cloud.githubusercontent.com/assets/6119878/9068328/794c7eb0-3aa8-11e5-97b9-080dd0d7c0ec.png)

**Comment by AgustinCB** [comment]
https://github.com/appsoma/welder/pull/227
