### ISSUE TITLE
welder_demo replies with error

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#231]
Perhaps I need to clear cookies?  In any case, the error message should be more 'friendly' if possible.

visit welder_demo.appsoma.com

{
    "message": "Key not found",
    "trace": [
        "Error",
        "    at exports.expressErrorHandler (/opt/welder/api/welder_utility.js:269:27)",
        "    at Layer.handle_error (/opt/welder/node_modules/express/lib/router/layer.js:58:5)",
        "    at trim_prefix (/opt/welder/node_modules/express/lib/router/index.js:300:13)",
        "    at /opt/welder/node_modules/express/lib/router/index.js:270:7",
        "    at Function.proto.process_params (/opt/welder/node_modules/express/lib/router/index.js:321:12)",
        "    at next (/opt/welder/node_modules/express/lib/router/index.js:261:10)",
        "    at Layer.handle_error (/opt/welder/node_modules/express/lib/router/layer.js:54:12)",
        "    at trim_prefix (/opt/welder/node_modules/express/lib/router/index.js:300:13)",
        "    at /opt/welder/node_modules/express/lib/router/index.js:270:7",
        "    at Function.proto.process_params (/opt/welder/node_modules/express/lib/router/index.js:321:12)"
    ],
    "status": 404,
    "path": "/",
    "error": "Key not found"
}

**Comment by AgustinCB** [comment]
Check the build script. It should be giving an error.

**Comment by AgustinCB** [comment]
And try npm install on ./widgets

**Comment by vernonm** [comment]
Welder demo still has un-committed changes in the directory.  Is it safe to check out and re-pull the contents, and destroy those changes?

**Comment by zsimpson** [comment]
Improved message.
