### ISSUE TITLE
Need to read marathon address from ZK

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#234]
To put marathon into High availablity mode welder will need to get the marathon address from ZK and it will have to deal with lead re-elections / fails.

**Comment by zsimpson** [comment]
See https://mesosphere.github.io/marathon/docs/high-availability.html

**Comment by vernonm** [comment]
Marathon runs on all masters, and doesn't have a  concept of leaders.  Name resolution will allow it to work
