### ISSUE TITLE
workflow name validation is incorrect at creation time

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#239]
When creating a new workflow via the UI, it doesn't do needed checking. Should use the same code that exists in the welder_plyer.js file and give a decent error message.

**Comment by zsimpson** [comment]
It does return a valid error. Are you saying you want client side checks on every thing everytwhere? That's a good idea but a tall order. Doing it piecemeal like this seems like a bad idea. We need a uniform validator concept or something.

**Comment by kdemarest** [comment]
When entering a new name, if it fails, the exception is a bit hard to
interpret. A dialog box clearly explaining would help a lot. Doesn't have
to check client-side...

*Ken Demarest*
ken.demarest@gmail.com
415.342.9731
Austin, Texas ▪ United States

**Comment by zsimpson** [comment]
Made the message more clear but it's stuff a weldererror returned to the normal ajax error dialog box
