### ISSUE TITLE
Plyers should not show complaints from log4j

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#250]
When running a java plyer, and zookeeper tries to log to log4j, this appears. However, such warnings should not clutter the view of the logs.

log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by zsimpson** [comment]
Fixed
