### ISSUE TITLE
Auto create of topics broken?

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#251]
On kelvin I had to stop and restart the plyer several times before it started working. I think it had to do with auto creatiopn of topics

**Comment by AgustinCB** [comment]
Uhm. Sounds strange. That should be a configuration value you set on kafka,
if it's set to true, should be working.

Maybe we can force that configuration value on code?

**Comment by vernonm** [comment]
On kelvin dev, I ended up initially installing a "new" version of kafka-mesos which could have messed up properties for kafka.  There might still be some pollution.

**Comment by vernonm** [comment]
I think its an error case that should at least be handled, since funky kafka configs might have that off..

**Comment by vernonm** [comment]
Did not repeat with a newer build of Kayak.  Maybe fixed?

**Comment by zsimpson** [comment]
Seemed to work on last try of welder_dev. Closing until it comes up again.
