### ISSUE TITLE
rhino not killing certain tasks

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#258]
bigTask7 should have been "killed" after bigTask0 failed (with exit code 2). However, notice that some of the other tasks depended on bigTask0 and they were properly killed.

![image](https://cloud.githubusercontent.com/assets/2153005/10299457/fa7b0e74-6baf-11e5-9411-7e8a2ed8cfa1.png)

**Comment by zsimpson** [comment]
Dupe
