### ISSUE TITLE
rhino multi-depend tasks not being killed

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#259]
bigTask16 should have been killed because it depends on 12 which depends on 0.

![image](https://cloud.githubusercontent.com/assets/2153005/10299496/5d55c070-6bb0-11e5-86a2-0db8ddc393a3.png)

**Comment by zsimpson** [comment]
Fixed. Problem was 2 fold. One if a dep died BEFORE the process even was posted it wasn't handled right. Also, I was traversing a cursor recursively that needed to be made into a list.
