### ISSUE TITLE
Not rebalancing right

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#260]
To repro...
Start up the scaler with scaling mode turned off -- so we can see the traces
Start up the plyer
Look at the plyer log.
Using marathon, scale the plyer to 2 instances, you see: ConsumerRebalanceFailedException
Now the scaler tracing shows that the topicis not balanced

**Comment by zsimpson** [comment]
http://stackoverflow.com/questions/23775087/kafka-single-consumer-failure-in-a-group

But I'm not seeing "conflict" in the logs. I'm not sure I'm looking at the right logs

**Comment by AgustinCB** [comment]
The solution they purpose in that link is increasing the timeout of Zookeeper. I saw in the past other use cases when that value was too low and made exceptions appear while coding kayak, so it's really possible that's related.

**Comment by zsimpson** [comment]
Fixed

**Comment by zsimpson** [comment]
The answer was the timesout in pump.java on our side -- I was over riding defaults based on random code form net.

**Comment by zsimpson** [comment]
Need to handle this exception right. Downgrading to p2

**Comment by zsimpson** [comment]
See #264
