### ISSUE TITLE
Sometimes somehow more than one record in the zk /gandalf/services for kayak

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#262]
Had to delete the first one to get it to connect from outside.

**Comment by zsimpson** [comment]
Saw it again today. No idea what happened. Had to shut down kayak, delete both records, restart kayak

**Comment by AgustinCB** [comment]
Fixed. The new version of gandalf is deployed to welder.dev.reactorsecurity.net. THere, the problem should be solved.
