### ISSUE TITLE
Saw error in scaler...

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#266]
APP EXCEPTION HTTP Error 409: {"message":"App is locked by one or more deployments. Override with the option '?force=true'. View details at '/v2/deployments/<DEPLOYMENT_ID>'.","deployments":[{"id":"0ca4ff6a-bddb-4b54-a9e9-c698bad0e61c"}]}

**Comment by vernonm** [comment]
This is probably a case of trying to change an app in marathon too fast (while it's still got an open deployment to implement the last change).

**Comment by zsimpson** [comment]
Interestingly it kept repeating. It happened when it was trying to get 4 machines but failing presumably because there weren't enough resources. Then it tried to scale down. So this seems like a fundamental problem in that it can't go up and can't go down. Need to trry that force=true option.

**Comment by zsimpson** [comment]
Repro even in marathon UI by scaling to more than can be allocated. Like 6. Then once the deploy has started but can't finish then set to less than currently exist.  It says the same message about force=true

**Comment by zsimpson** [comment]
Seems fixed with the force option
