### ISSUE TITLE
Sometimes kayak doesn't restart on deploy

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#275]
Mark not sure what the symptoms are.

**Comment by vernonm** [comment]
This appears to be related to initial deploy issues with HAProxy/Gandalf and the creation of zookeeper entries.  If Zookeeper entries aren't available the curl call to Marathon will fail (no marathon URL will be retrieved from ZK).

**Comment by vernonm** [comment]
Seems to be working.
