### ISSUE TITLE
plyer pump exceptions should appear on the trace

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#276]
It used to be true that all plyer pump exceptions were caught in the outer framework, and pushed onto the trace topic, so that users could readily tell when there was an error.

The format was:
{ error: { all keys and values of the error, including a stack trace } }

**Comment by zsimpson** [comment]
done for java now. Python is another matter. Currentl python implementaiton expects the python to spit out good json so the python would have to do this itself.
