### ISSUE TITLE
microbiome_pipeline generate_lastal_jobs starting jobs very slowly...

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#281]
Like 40-60 seconds per job. Those should be very fast.

**Comment by vernonm** [comment]
My first guess would be NFS.

------ Original Message ------

**Comment by zsimpson** [comment]
Started a new sync on demo so that I'll be able to test this there. Awaiting that sync to finish.

**Comment by zsimpson** [comment]
Sync done, need to start jobs now

**Comment by zsimpson** [comment]
Problem was slave running on master stealing memory/cpu from welder. Just a bad idea I think to run slaves on master in produciton.
