### ISSUE TITLE
Need mesosURL in the welder config

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#293]
welder_duke now going to make calls to mesos to figure out slave state. Need the url. (I'm goin gto work around for the time being by using the marathonURL and changing its port).

**Comment by vernonm** [comment]
master.mesos:5050 if we're using mesos_dns.  Same can be said for marathonURL now too.  Do we want a specific config value?

**Comment by zsimpson** [comment]
I'll just use that for now. Closing this and we can re open if we later want to have it configurable.
