### ISSUE TITLE
Clarity on java sandboxing

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#298]
http://www.jayway.com/2014/06/13/sandboxing-plugins-in-java/

http://docstore.mik.ua/orelly/java-ent/security/ch01_02.htm

https://docs.oracle.com/cd/E19636-01/819-1655/egkdm/index.html

http://www2.datenwerke.net/files/sandbox/0.3/doc/overview-summary.html

**Comment by zsimpson** [comment]
Resolved
