### ISSUE TITLE
Overlaid panels, like "task info" should leave a ~60px margin from bottom, as well as top.

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#3]

**Comment by zsimpson** [comment]
I don't know what this means. The bottom expands according to the dialog size.

**Comment by kdemarest** [comment]
Here is what I mean. In the screen shot below, the bottom of the dialog is off the window AND there is no way for me to scroll down to it (actually there is a hacky way: if I highlight an area and move my mouse down it scrolls, and there after it seems to understand that it should scroll. But not before).'

So my suggestion is this: make the "Choose Files" area compress smaller vertically when the window height is less.

![image](https://cloud.githubusercontent.com/assets/2153005/7600775/710c3bca-f8d4-11e4-94e4-aba87bc2a0d5.png)

**Comment by zsimpson** [comment]
I get a scroll bar on the right when I overflow.  Are you sure there isn't one of those hidden scroll bars in OSX?  IOf you two finger scroll does it go down?

**Comment by kdemarest** [comment]
OK, the repro case is CRAZY:

- open a new tab in the browser
- start with window tall (too tall to scroll)
- load page http://mesos.appsoma.com:8088/projects/zack/apps/bwa
- click to select ref genome
- try to scroll
-> no scroll bar appears (which is OK, cause its tall)
- resize window short
- reload page
- click to select ref genome
-> can not scroll

I am about to try to repro with no other tabs open.  This will probably be a super rare problem, so after I test again I'll probably p4 it.

**Comment by kdemarest** [comment]
The bug is 100% repro on my MacBook Air OSX 10.10.1 in Chrome 42.0.2311.135 (64-bit)

But resizing the window in any way makes it scroll again.

**Comment by kdemarest** [comment]
Wait, I've got an even simpler repro case. This is fixable.

1. First, size your browser so its height would result in this at the bottom:

![image](https://cloud.githubusercontent.com/assets/2153005/7614274/5b1c76f4-f95b-11e4-9fda-74c1b711813f.png)

2. Start a blank tab
3. Load the page http://mesos.appsoma.com:8088/projects/zack/apps/bwa
4. It won't scroll.

I think that maybe inserting the "Upload" section into the dialog makes the dialog taller, but somehow the page doesn't realize that it got taller. I think that if you forced a call to the page resize handler it would figure it out...

**Comment by kdemarest** [comment]
Seemingly a known issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=927702

OK, it is more subtle than shown, and intermittent. Using up and down arrow works. Only the two-finder scroll has the problem, and only sometimes.  My only suggestion is to call window.onresize()

**Comment by zsimpson** [comment]
@kdemarest When do you suggest the call trigger onreize?  After the dialog is open?

**Comment by kdemarest** [comment]
Yes, I think so... But not sure this is fixable, or worth trying to fix.
