### ISSUE TITLE
All dialog forms

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#32]
needs tobe done with some fucntion that make s aform so that ENTER works and also focuses the top line when the form appears

**Comment by zsimpson** [comment]
I spent some time on this and got nowhere. I tried to put the ok button inside the form and then bind if .submit.  For mysterious reasons ENTER would then close the dialog but not trigger the form submit.

I'm giving up on this for now. Closing.

**Comment by AgustinCB** [comment]
https://github.com/appsoma/welder/pull/192
