### ISSUE TITLE
Kens' demos not working in new demo_project

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#40]
Something about apps/ paths

**Comment by kdemarest** [comment]
They probably have base=... In the html

On Saturday, May 30, 2015, Zack Booth Simpson <notifications@github.com>
wrote:

> Something about apps/ paths
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appsoma/welder/issues/40>.
>


-- 
*Ken Demarest*
*CEO, Appsoma *
ken@appsoma.com
415.342.9731
Austin, Texas ▪ United States

**Comment by zsimpson** [comment]
That was it, thanks!
