### ISSUE TITLE
Run Similar

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#56]
The list of runs needs a link on the right [Run similar]

Suggestions:
* In the app's index.json file there should be an entry `run_similar: true` if the app is capable of running based on similar params
* Welder should provide a tiny form_populate() function that takes a json block and plugs values into a form (user must call this manually after document ready)
* Running based on similar is probably not inherent to welder. The site is capable of seeing
`/projects/virus_mgt/apps/bwa/index.html?run_similar=0023` and knowing how to fetch that runs params.

**Comment by zsimpson** [comment]
Done
