### ISSUE TITLE
Feature: a widget that shows how tasks many are running

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#67]

**Comment by talli** [comment]
can you use something like Dashing or Tipboard to make those widgets pretty?

http://shopify.github.io/dashing/
http://allegrotech.io/tipboard/

--
Talli Somekh
Musea Ventures
talli@museaventures.com
Phone: +1 917 940 9864
Skype: tallisomekh
Twitter: @ <http://twitter.com/talli>talli

**Comment by kdemarest** [comment]
For the "real" dashboards, that is the direction. We won't be a dashboard
creation framework. But to give users an uncomplicated, at-a-glance view
we'd make a little 40 line widget.

*Ken Demarest*
*CEO, Appsoma *
ken@appsoma.com
415.342.9731
Austin, Texas ▪ United States
