### ISSUE TITLE
Nav bar collapses wrong

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#73]
Instead of becoming a three line icon, it now collapses into vertical, as shown below

![image](https://cloud.githubusercontent.com/assets/2153005/8015883/626bb68c-0ba2-11e5-858a-efaa2d9e5542.png)

**Comment by zsimpson** [comment]
Looks like this is quite a pain.  Apparently I have to change the @grid-float-breakpoint in LESS which means I have the download a new CSS which means we can't use the CDN.

**Comment by appsoma-repos-user** [comment]
No just redeclare it in our css I think. No?

On Friday, June 5, 2015, Zack Booth Simpson <notifications@github.com>
wrote:

> Looks like this is quite a pain. Apparently I have to change the
> @grid-float-breakpoint in LESS which means I have the download a new CSS
> which means we can't use the CDN.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appsoma/welder/issues/73#issuecomment-109487335>.
>


-- 
*Ken Demarest*
*CEO, Appsoma *
ken@appsoma.com
415.342.9731
Austin, Texas ▪ United States

**Comment by zsimpson** [comment]
That symbol (which I don't think is a CSS symbol) shows up only in the .less and .map files. I don't think we can add it to CSS. Do you know something I don't?

**Comment by kdemarest** [comment]
No you're right. I deeply lve that we use unaltered bootstrap. I'd rather have a code or css solution if humanly possible, or just let it collapse.

For reference:
http://stackoverflow.com/questions/18192082/bootstrap-3-navbar-collapse

**Comment by zsimpson** [comment]
Closing this, starting a new issue about refactoring this bar

**Comment by appsoma-repos-user** [comment]
i know how to fix - eg i did some custom work in css

On Friday, September 25, 2015, Zack Booth Simpson <notifications@github.com>
wrote:

> Closing this, starting a new issue about refactoring this bar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appsoma/welder/issues/73#issuecomment-143344187>.
>


-- 
*Ken Demarest*
*CEO, Appsoma *
ken@appsoma.com
415.342.9731
Austin, Texas ▪ United States
