### ISSUE TITLE
Rhino, look up master in zookeeper

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#74]
I've made an assuming on my mesos request that the zk and mesos master are on the same IP.  This is a wrong assumption but will get me error checking faster.

**Comment by zsimpson** [comment]
Looks like this is a populart python binding
https://kazoo.readthedocs.org/en/latest/

**Comment by zsimpson** [comment]
Experimented with this. Turns out to be tricky. There's a CLI
mesos-resolve but it isn't installed in the rhino container so I can't call it.
Other options including adding other things like the above python bindings to the rhino container.
Demoting to p2 for now.

**Comment by vernonm** [comment]
There are zookeeper API bindings too, that might be more useful.  Perhaps assume it's at /mesos (or pass the path as argument+ and maybe you can parse the results of a get.

**Comment by zsimpson** [comment]
@vernonm Didn't you do this? Can we close

**Comment by vernonm** [comment]
I think it's functional.  using mesos resolve in rhino.

**Comment by vernonm** [comment]
This probably just needs to be master.mesos, since we're using mesos-dns

**Comment by vernonm** [comment]
Rhino uses proper DNS
