### ISSUE TITLE
need script to update the clusters

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#79]
when I push to dev or demo I need a script.

**Comment by vernonm** [comment]
Added to the ansible-appsoma-mesos repo: https://github.com/appsoma/ansible-appsoma-mesos/blob/master/playbooks/welder_playbook.yml

To run: 
`ansible-playbook --private-key ~/vmmy.pem -i inventory/ec2Inventory.py playbooks/welder_playbook.yml`

**Comment by zsimpson** [comment]
This works ok for demo/production but not so much for development where it needs a git checkout . before it pulls.  I'm going to add a separate script for this
