### ISSUE TITLE
To run welder tests, I have to have node and welder on the NFS server

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#85]
Or at least have an NFS mount over to the welder code.

:-(

**Comment by vernonm** [comment]
Added to the ansible scripts the ability to test welder https://github.com/appsoma/ansible-appsoma-mesos/commit/0cdec50e46ac20391a787b165222b1b8513acba2

To use, from the ansible checkout:

`ansible-playbook --private-key ~/vmmy.pem -i inventory/ec2Inventory.py playbooks/welder_test_playbook.yml -e welder_branch=dev`

`welder_branch=` is optional, leaving it out will use HEAD (master).  It could also be any version or tag.

To use as part of complete_deploy:

`ansible-playbook --private-key ~/vmmy.pem -i inventory/ec2Inventory.py create_cluster_playbook.yml -e "test_welder=true welder_branch=dev master_count=1 slave_count=1"`

**Comment by zsimpson** [comment]
I'm refactoring the tests to use welder polling instead.
