### ISSUE TITLE
Take "portal" off main menu

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#91]
Shall we get rid of this now that we have bluer? I think it's confusing.

**Comment by appsoma-repos-user** [comment]
Well, when a developer checkmarks an app to be visible to end users, he
would still want to be able to see what a user would see. I think on the
Apps tab we should put a button at the top-right "View in Portal".

*Ken Demarest*
*CEO, Appsoma *
ken@appsoma.com
415.342.9731
Austin, Texas ▪ United States

**Comment by zsimpson** [comment]
Done
